---
- hosts: all
  become: true
  tasks:
    - name: Configure time synchronization
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: time.cloudflare.com
            iburst: true
