---
- hosts: all
  become: true
  tasks:
    - name: Create svc-veeam group
      ansible.builtin.user:
        name: svc-veeam
        uid: 20002
    - name: Create svc-veeam user
      ansible.builtin.user:
        name: svc-veeam
        uid: 20002
        group: svc-veeam
    - name: Set svc-veeam ssh keys
      ansible.posix.authorized_key:
        user: svc-veeam
        exclusive: yes
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAl0J6kUYohweeNoKnVakJqLrTxyaEIFR2g3M+f61z4l svc-veeam@veeam01.ad.ryacom.org'
    - name: Add svc-veeam to sudoers
      community.general.sudoers:
        name: svc-veeam
        user: svc-veeam
        commands: ALL
